name: Lint code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]


jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
